### ISSUE TITLE
Incorrect description in javadoc of EJBTransactionRolledbackException

### ISSUE THREAD

**Issue by chengfang** [eclipse-ee4j/ejb-api#116]
[EJBTransactionRolledbackException](https://github.com/eclipse-ee4j/ejb-api/blob/master/api/src/main/java/jakarta/ejb/EJBTransactionRolledbackException.java) class description states:

> This exception is thrown to a remote client to indicate that the
> transaction associated with processing of the request has been
> rolled back, or marked to roll back.

But this exception can be thrown to both remote and local client of ejb business methods. So we may need to remove the word "remote", and probably replace it with something like "is thrown to a caller of bean business method to indicate ..."

**Comment by hussainnm** [comment]
As per specification, [Section 9.3.6](https://jakarta.ee/specifications/enterprise-beans/4.0/enterprise-beans-spec-core-4.0-public-draft.html#exceptions-from-other-container-invoked-callbacks) `EJBTransactionRolledbackException` should be thrown if instance is part of client's transaction, otherwise for a remote client `jakarta.transaction.TransactionRolledbackException` is thrown and for a local client `jakarta.ejb.TransactionRolledbackLocalException` is thrown.

**Comment by chengfang** [comment]
@hussainnm the spec section you quoted supports the claim of this issue, that is, `EJBTransactionRolledbackException` is intended for both remote and local invocations of ejb business methods, and therefore, its javadoc needs to be updated to reflect that. I suspect the javadoc description was an oversight.

**Comment by hussainnm** [comment]
My understanding is when the `EJBTransactionRolledbackException` and `TransactionRolledbackLocalException` were introduced in 2.0, one was meant for remote client and the other was meant for local client. `EJBTransactionRolledbackException` should be thrown if and only if the business interface does not extend `java.rmi.Remote` in remote client otherwise it should throw `jakarta.transaction.TransactionRolledbackException`.

**Comment by chengfang** [comment]
This is how I understand it:

EJB 2.x:
remote client: `jakarta.transaction.TransactionRolledbackException`
local client: `jakarta.ejb.TransactionRolledbackLocalException`

EJB 3:
any client (both remote and local) of ejb that does not extend `java.rmi.Remote` (that is 99.9% of case): `EJBTransactionRolledbackException`.  This is the focus of this issue.  Any ejb3 beans that extend `java.rmi.Remote` is rare case and for practical purpose, we can just ignore it.

**Comment by hussainnm** [comment]
Ok, got it.

**Comment by jeanouii** [comment]
Hey @chengfang I think we are good with this issue now. Can we close?

**Comment by chengfang** [comment]
The fix has been merged and this issue is resolved.
