### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/ejb-api#33]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by arjantijms** [comment]
@m0mus 

EJB 3.2.3 is already released: https://repo1.maven.org/maven2/jakarta/ejb/jakarta.ejb-api/3.2.3/

There's a 3.2.4 branch here, but isn't that a mistake by the re-staging or bot? There are no additional commits in the 3.2.4 branch.

The problem is that this projects depends on JTA 1.3.1, but JTA has released a 1.3.2:

https://repo1.maven.org/maven2/jakarta/transaction/jakarta.transaction-api/1.3.2/

**Comment by arjantijms** [comment]
@m0mus I guess we can close this issue as done, and then update the GF component tracker to state that 3.2.3 is the released component version?

**Comment by m0mus** [comment]
https://repo1.maven.org/maven2/jakarta/ejb/jakarta.ejb-api/3.2.4/
