### ISSUE TITLE
Change project name to Jakarta Enterprise Beans

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/ejb-api#38]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [x]  GitHub
- [x]  README file
- [x]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
Any objections to Jakarta Enterprise Beans?

**Comment by tkburroughs** [comment]
While JEB or Jeb does seem like a nice acronym, that does pose a bit of a problem for the well established EJB acronym.... as well as the fact that the API package is javax.ejb, and many of the interfaces start with EJB, and the annotation is EJB.

However, since every other Jakarta specification will start with Jakarta, would it really be that important to have this one spec not adopt the convention, and go with Enterprise Jakarta Beans?

In the renamed version of the specification, could the introduction just indicate that it covers "enterprise beans" and for compatibility purposes, the API will refer to them as "enterprise (Jakarta) beans"? Or something like that.

**Comment by bshannon** [comment]
We actually have to stop using the "EJB" acronym, so Jakarta Enterprise Beans is better.

**Comment by kwsutter** [comment]
This time I do agree with @bshannon...  :-)  EJB is a Registered TM of Oracle and we'll have to stop using it to describe new capabilities after the technology moves to Jakarta.  We can still use EJB to refer to the past Java EE EJB technology -- as long as we give it proper attribution.

To be consistent with the rest of the Specification Projects being proposed, I would prefer to go with something Jakarta Enterprise Beans.

**Comment by ivargrimstad** [comment]
**Jakarta Enterprise Beans** it is...
