### ISSUE TITLE
Remove "jakarta.transaction" classes from ejb-api JAR

### ISSUE THREAD

**Issue by tkburroughs** [eclipse-ee4j/ejb-api#78]
The "jakarta.ejb-api-4.0.0-RC1.jar" API jar contains classes from the "jakarta.transaction" package.   They also show up in the javadoc jar as well.

https://jakarta.oss.sonatype.org/content/repositories/releases/jakarta/ejb/jakarta.ejb-api/4.0.0-RC1/

The "jakarta.transaction" package should just be a dependency, not an include.

**Comment by hussainnm** [comment]
The glassfishbuild-maven-plugin is adding the project dependencies into the source. This was previously used to pull in xml-rpc-api sources. I have removed the plugin from pom.xml. 

Also I have removed the unnecessary dependency to cdi-api. This was added to compile the project because of the regression caused by the above plugin.
